blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('user/<str:username>', views.UserPostIndexView.as_view(), name='user-posts'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('blog/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('blog/create/', views.PostCreateView.as_view(), name='create'),
    path('blog/<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('blog/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

django_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    # Password Reset URLs
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views as user_views

app_name = 'users'

urlpatterns = [
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', user_views.ProfileView.as_view(), name='profile'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
# from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='posts')

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return f'{self.title}: {self.content[:100]}'

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from users.models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from django.shortcuts import get_object_or_404

from django.views.generic import (
    ListView,
    TemplateView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from blog.models import Post


class IndexView(ListView):
    template_name = 'blog/index.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 2


class UserPostIndexView(ListView):
    template_name = 'blog/user_posts.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 1

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return user.posts.all().order_by('-date_posted')


class AboutView(TemplateView):
    template_name = 'blog/about.html'


class PostDetailView(DetailView):
    template_name = 'blog/detail.html'
    model = Post
    context_object_name = 'post'


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'blog/blog_form.html'
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'blog/blog_form.html'
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'blog/post_confirm_delete.html'
    model = Post
    success_url = '/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from users.forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


class RegisterView(SuccessMessageMixin, generic.CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('blog:index')
    template_name = 'users/register.html'
    success_message = f" was created successfully!"

    def get_success_message(self, cleaned_data):
        username = cleaned_data['username']
        return f'{ username } has been registered!'


class ProfileView(LoginRequiredMixin, generic.View):
    """Form to edit a user profile. It uses generic.View because it contains two forms."""
    template_name = 'users/profile.html'

    def get(self, request):
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

        context = {'u_form': u_form, 'p_form': p_form}
        return render(request, 'users/profile.html', context)

    def post(self, request):
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'The user has been updated.')
        else:
            messages.warning(request, 'The profile has not been updated')

        return redirect('users:profile')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog:index' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog:index' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'users:profile' %}">{{ user.username }}</a>
                <a class="nav-item nav-link" href="{% url 'blog:create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
              {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/blog/about.html
{% extends 'base.html' %}
{% block content %}
<h1>ABOUT</h1>
{% endblock %}

templates/blog/blog_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method='post' novalidate>
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                {% if object.title %}
                    {{ object.title }}
                {% else %}
                    New Post
                {% endif %}
            </legend>
            {{ form|crispy }}
        </fieldset>
        <button class="btn btn-outline-info" type="submit">Post</button>
    </form>
</div>
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
    <article class="media content-section">
        <img src="{{ post.author.profile.image.url }}" alt="{{ post.author.username }}" class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
                <a href="{% url 'blog:user-posts' post.author.username %}" class="mr-2">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:'F d, Y' }}</small>
                {% if post.author == user %}
                <div>
                    <a href="{% url 'blog:update' post.pk %}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
                    <a href="{% url 'blog:update' post.pk %}" class="btn btn-danger btn-sm mt-1 mb-1">Delete</a>
                </div>
                {% endif %}
            </div>
            <h2><a href="#" class="article-title">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a href="#" class="mr-2">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:'F d, Y' }}</small>
                </div>
                <h2><a href="#" class="article-title">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock %}

templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method='post' novalidate>
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete {{ object.title }}</h2>
        </fieldset>
        <button class="btn btn-outline-danger" type="submit">Delete</button>
        <a class="btn btn-outline-secondary" href="{ url 'blog:detail' object.pk }">Cancel</a>
    </form>
</div>
{% endblock %}

templates/blog/user_posts.html
{% extends 'base.html' %}
{% block content %}
    <h1>Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
            <img src="{{ post.author.profile.image.url }}" alt="{{ post.author.username }}" class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a href="{% url 'blog:user-posts' post.author.username %}" class="mr-2">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:'F d, Y' }}</small>
                </div>
                <h2><a href="{% url 'blog:detail' post.pk %}" class="article-title">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    {% endif %}
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method='post' novalidate>
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            {{ form|crispy }}
        </fieldset>
        <button class="btn btn-outline-info" type="submit">Log In</button>
    </form>
    <div class="border-top pt-3 mt-3">
        <small class="text-muted">Need An Account?<a href="{% url 'users:register' %}" class='ml-2'>Sign Up!</a></small>
    </div>
</div>
{% endblock %}

templates/users/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method='post' novalidate>
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            {{ form|crispy }}
        </fieldset>
        <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
    </form>
</div>
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'users:login' %}">Sign In Here!</a>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method='post' novalidate>
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            {{ form|crispy }}
        </fieldset>
        <button class="btn btn-outline-info" type="submit">Reset Password.</button>
    </form>
</div>
{% endblock %}

templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
    <div class="alert alert-info">
        Your password has been sent with instruction on how to reset your password.
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
      <form method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{ u_form|crispy }}
        {{ p_form|crispy }}
        <button class="btn btn-outline-info" type="submit">Update</button>
      </form>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method='post' novalidate>
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <button class="btn btn-outline-info" type="submit">Sign Up</button>
    </form>
    <div class="border-top pt-3 mt-3">
        <small class="text-muted">Already Have An Account?<a href="#" class='ml-2'>Login</a></small>
    </div>
</div>
{% endblock %}